### ISSUE TITLE
[Feature] Support checking permissions against class

### ISSUE THREAD

**Issue by ackerdev** [vdemedes/cancan#2]
It would be nice to be able to do:
```js
class Product {}
can(user, 'view', Product);
```
This check should most likely ignore conditions on rules, so for instance the above would return true even if the rule was defined as `this.can('view', Product, { id: user.id })`

**Comment by vdemedes** [comment]
Hm, could you provide a real use-case? I am struggling to find any.

**Comment by ackerdev** [comment]
eg. a REST API with a `GET /products/` route, that returns a list of products. Being able to test permissions of the current user against the Product class is important as you aren't working with a single Product instance.

**Comment by vdemedes** [comment]
Yeah, good point. Will implement that, thanks for suggestion ;)

**Comment by ackerdev** [comment]
I've also gone ahead and added #3 which goes hand-in-hand with this.

I may submit a PR for either of these soon, but feel free to go ahead with it if you feel you're interested in it and feel you'll be faster about it :)

**Comment by vdemedes** [comment]
I see how this feature would benefit developers, but I am not sure about the #3. Will have to think about it later ;)

**Comment by ackerdev** [comment]
#3 is convenient for similar reasons; when you want to retrieve your list of products, you don't have an instance to work with, you need to make a query to your database, so being able to retrieve your conditions to put them in say your sql-where clause is extremely useful.

**Comment by vdemedes** [comment]
Implemented and pushed this feature to npm as `cancan@2.0.0`. Thanks!

**Comment by ackerdev** [comment]
No, thank you :smiley:
