### ISSUE TITLE
not able to NPM install

### ISSUE THREAD

**Issue by markeySorenson** [vdemedes/cancan#22]
Good morning,

My build server just logged this error message which is a dependancy of cancan. Just wondered if you could look into it please?

STDOUT: npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'jkroso/type' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'equals'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

I believe if you lock the version of equals to 1.0.1 (remove the ^), this should fix the issue.

Many thanks.

**Comment by vdemedes** [comment]
Hey, I can't reproduce this issue with the latest master or npm published version. Are you using some proxy/npm proxy/etc?

**Comment by markeySorenson** [comment]
Thanks you for looking, our build server (OpsWorks) was running at node version 0.10.29 which no longer works with recent changes on the equals package.
