### ISSUE TITLE
Support Sequelize ORM

### ISSUE THREAD

**Issue by ackerdev** [vdemedes/cancan#5]
Sequelize model instances, unfortunately, do not properly support the `constructor` property (It returns an anonymous factory from Sequelize core, not the Model class). However, they do have a `Model` property that does return the Model class.

Sequelize Models also are objects, not functions, meaning they weren't properly affected by [this patch](https://github.com/vdemedes/cancan/commit/796c7fcdaf824d69d69682fb3dd2f5e140f4b9b4#diff-168726dbe96b3ce427e7fedce31bb0bcR243).

It might be worth looking into setting up an adapter pattern for supporting ORMs that do these kind of strange things.

**Comment by vdemedes** [comment]
I think there should be a method in cancan, that you can override to support custom types of models. Good point!

**Comment by vdemedes** [comment]
Fixed in latest cancan, usage for sequelize:

```js
cancan.instanceOf = function (instance, model) {
  return instance instanceof model.Instance;
};
```

**Comment by yassinMk** [comment]
Hi @ackerdev,

can you give me an example, how to use this package with sequelize ?
Thanks.

**Comment by vadimdemedes** [comment]
Hey @yassinMk, CanCan got updated since, so posted code won't work anymore. Try this instead (for `cancan@3`):

```js
const cancan = new CanCan({
	instanceOf(instance, model) {
		return instance instanceof model.Instance;
	}
});

const {allow, can, cannot} = cancan;
```
